{
 "title": "asp.net app dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "controllers",
    "label": "Controllers",
    "query": {
     "query": "label_values(http_requests_received_total, controller)"
    }
   },
   {
    "name": "actions",
    "label": "Actions",
    "query": {
     "query": "label_values(http_requests_received_total{controller=~ \"$controllers\"}, action)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "quantile estimations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(http_request_duration_seconds_bucket{controller=~\"$controllers\", action=~\"$actions\"}[$__range])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(increase(http_request_duration_seconds_bucket{controller=~\"$controllers\", action=~\"$actions\"}[$__range])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(http_request_duration_seconds_bucket{controller=~\"$controllers\", action=~\"$actions\"}[$__range])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(increase(http_request_duration_seconds_bucket{controller=~\"$controllers\", action=~\"$actions\"}[$__range])) by (le))",
     "legendFormat": "p99.9"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(increase(http_request_duration_seconds_bucket{controller=~\"$controllers\", action=~\"$actions\"}[$__range])) by (le))",
     "legendFormat": "p99.99"
    }
   ]
  },
  {
   "title": "request durations",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{controller=~\"$controllers\", action=~\"$actions\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "req/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{controller =~ \"$controllers\", action=~\"$actions\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "request duration",
   "type": "heatmap",
   "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!\n\nMin step is 5m.\n\n$__rate_interval multiplied actual results for some reason.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{controller=~\"$controllers\", action=~\"$actions\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "stats by endpoint",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum without (code) (increase(http_requests_received_total{controller=~\"$controllers\"}[$__range]))"
    },
    {
     "expr": "(\nsum without (code) (increase(http_request_duration_seconds_sum{controller=~\"$controllers\"}[$__range]))\n) / (\nsum without (code) (increase(http_request_duration_seconds_count{controller=~\"$controllers\"}[$__range]))\n)"
    }
   ]
  }
 ]
}