namespace Infra.FunTranslations.Responses;

#nullable disable

/// <summary>
/// Autogenerated. do not change
/// </summary>
public class FunTranslationErrorResponse
{
    public Error error { get; set; }
}

public class Error
{
    public int code { get; set; }
    public string message { get; set; }
}
#nullable enable
