apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    orgId: 1
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"