namespace Infra.PokeApi;
/// <summary>
/// Autogenerated. do not change
/// </summary>
#nullable disable
public class PokeApiResponse
{
    public Data data { get; set; }
}

public class Data
{
    public Pokemon_V2_Pokemonspecies[] pokemon_v2_pokemonspecies { get; set; }
}

public class Pokemon_V2_Pokemonspecies
{
    public string name { get; set; }
    public bool is_legendary { get; set; }
    public Pokemon_V2_Pokemonhabitat pokemon_v2_pokemonhabitat { get; set; }
    public Pokemon_V2_Pokemonspeciesflavortexts[] pokemon_v2_pokemonspeciesflavortexts { get; set; }
}

public class Pokemon_V2_Pokemonhabitat
{
    public string name { get; set; }
}

public class Pokemon_V2_Pokemonspeciesflavortexts
{
    public string flavor_text { get; set; }
}

#nullable enable
